<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string></string>
	<key>fileTypes</key>
	<array>
		<string>auth</string>
		<string>cl</string>
		<string>l</string>
		<string>mud</string>
		<string>el</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\(</string>
	<key>foldingStopMarker</key>
	<string>\)</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>auth</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.auth</string>
				</dict>
			</dict>
			<key>match</key>
			<!-- COMMENT -->
			<string>((\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{6}.\d{2}:\d{2} icu-f01 CRON\[\d+\]:)|(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{6}.\d{2}:\d{2} icu-f01 Generic_client.*CONNECT FAILED\-\-crew display)).*$\n?</string>
			<key>name</key>
			<string>comment.line.semicolon.auth</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.function-type.auth</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.auth</string>
				</dict>
			</dict>
			<key>match</key>
			<!-- META FUNCTION -->
			<!-- <string>(\b(icu-f01)\b)(\s+)((\w|\-|\!|\?)*)</string> -->
			<string>(\b(icu-f01)\b)(\s+)((Cumain|Generic_client|Telem|RIC_mgr)\sv2\.00)</string>
			<key>name</key>
			<string>meta.function.auth</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.auth</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#)(\w|[\\+-=&lt;&gt;'"&amp;#])+</string>
			<key>name</key>
			<string>constant.character.auth</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.auth</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.auth</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\*)(\S*)(\*)</string>
			<key>name</key>
			<string>variable.other.global.auth</string>
		</dict>
		<dict>
			<key>match</key>
			<!-- KEYWORD CONTROL -->
			<!-- <string>^(\d{4}-\d{2}-\d{2})T(\d{2}:\d{2}:\d{2}\.\d{6}.\d{2}:\d{2})|No input.*Waiting 240 more|HASTA_LA_VISTA_BABY|(?i:fail|error)</string> -->
			<string>No (input|connection).*(Waiting 240 more|QUITTING|Quitting)|HASTA_LA_VISTA_BABY|Saying goodbye now|(?i:fail|error|bad)</string>
			<key>name</key>
			<string>keyword.control.auth</string>
		</dict>
		<dict>
			<key>match</key>
			<!-- KEYWORD OPERATOR -->
			<string>\b(?i:eq|kernel)\b</string>
			<key>name</key>
			<string>keyword.operator.auth</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:PURPLE|tshes-0\d|12(1|2)\-f0\d)\b</string>
			<key>name</key>
			<string>constant.language.auth</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bicu-f01\b</string>
			<key>name</key>
			<string>support.function.auth</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\btshes-0\d\b</string>
			<key>name</key>
			<string>constant.numeric.auth</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\d{4}</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.auth</string>
				</dict>
			</dict>
			<key>end</key>
			<string>T</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.auth</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.auth</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.auth</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.auth</string>
	<key>uuid</key>
	<string>eaf56b8f-0183-42f2-8971-f879e6f452e2</string>
</dict>
</plist>
